version: '3.5'

services:
  seeder-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: seeder-app
    environment:
      - APACHE_RUN_USER=${DOCKER_USER_NAME}
      - APACHE_RUN_GROUP=${DOCKER_USER_NAME}
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    networks:
      backend:
        aliases:
          - seeder-app


  seeder_composer_installation:
    container_name: seeder_composer_installation
    image: composer
    volumes:
      - ./:/app
    command: composer install --ignore-platform-reqs









  mysql-database:
    image: mysql:5.7
    container_name: mysql-database
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - seeder_database

  seeder-phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - mysql-database
      environment:
        PMA_HOST: mysql-database
        PMA_PORT: 3306
      ports:
        - 8080:80
      networks:
        backend:
          aliases:
            - phpmyadmin

networks:
  backend:
    name: seeder_backend-network
